export const SITE_URL = "https://anywaypossible.com";
export const PAY_TO = "0xe5690D37805107C56f6195E65A262b234E0E5e75";
export const NETWORK = "eip155:8453";
export const USDC = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913";

const address = { type: "string", pattern: "^0x[a-fA-F0-9]{40}$" };
const url = { type: "string", format: "uri" };
const timestamp = { type: "string", format: "date-time" };

export const tools = [
  {
    id: "merchant-snapshot",
    name: "Merchant Snapshot",
    mcpTool: "merchant_snapshot",
    operationId: "snapshotX402Merchant",
    tag: "SELLER INTELLIGENCE",
    question: "Why is my x402 API not selling?",
    useWhen: "A merchant needs a fast, evidence-backed diagnosis before buying a full audit.",
    description: "Diagnose an x402 merchant using Bazaar visibility, buyer signals, payment reliability, and observed Base USDC activity, then return the largest revenue issue.",
    priceUsd: 0.05,
    price: "$0.05",
    amountAtomic: "50000",
    endpoint: "/api/merchant-snapshot",
    maxTimeoutSeconds: 60,
    sampleRequest: { payTo: PAY_TO, queries: ["x402 merchant analytics", "increase x402 revenue"] },
    sampleResponse: { score: 86, grade: "B", biggestIssue: "Improve buyer-search visibility.", upgrade: { endpoint: `${SITE_URL}/api/merchant-audit`, priceUsd: 0.25 } },
    inputSchema: { type: "object", additionalProperties: false, required: ["payTo", "queries"], properties: { payTo: address, queries: { type: "array", minItems: 1, maxItems: 3, items: { type: "string", minLength: 2, maxLength: 100 } }, excludePayers: { type: "array", maxItems: 10, items: address } } },
    outputSchema: { type: "object", required: ["snapshotId", "merchant", "network", "observedAt", "score", "grade", "signals", "visibility", "biggestIssue", "upgrade", "limitations"], properties: { snapshotId: { type: "string" }, merchant: { type: "string" }, network: { type: "string" }, observedAt: timestamp, score: { type: "integer", minimum: 0, maximum: 100 }, grade: { type: "string", enum: ["A", "B", "C", "D", "F"] }, signals: { type: "object" }, visibility: { type: "array", items: { type: "object" } }, biggestIssue: { type: "string" }, upgrade: { type: "object" }, limitations: { type: "array", items: { type: "string" } } } },
  },
  {
    id: "treasury",
    name: "Treasury",
    mcpTool: "treasury_preflight",
    operationId: "preflightBaseUsdcPayment",
    tag: "PAYMENT PREFLIGHT",
    question: "Is this Base payment safe and funded?",
    useWhen: "An agent needs a proceed, fund, review, or reject decision before signing.",
    description: "Check Base funding, gas, chain intent, destination type, and common payment hazards before an agent signs.",
    priceUsd: 0.02,
    price: "$0.02",
    amountAtomic: "20000",
    endpoint: "/api/treasury",
    maxTimeoutSeconds: 60,
    sampleRequest: { address: "0x1111111111111111111111111111111111111111", destinationAddress: "0x2222222222222222222222222222222222222222", plannedSpendUsdc: "1.00", expectedChainId: 8453 },
    sampleResponse: { decision: "needs_funding", safeToProceed: false, riskLevel: "medium", recommendedAction: "Fund the wallet before paying." },
    inputSchema: { type: "object", additionalProperties: false, required: ["address"], properties: { address, destinationAddress: address, plannedSpendUsdc: { type: "string", pattern: "^[0-9]+(\\.[0-9]{1,6})?$", default: "1.00" }, minGasReserveEth: { type: "string", pattern: "^[0-9]+(\\.[0-9]{1,18})?$", default: "0.00005" }, expectedChainId: { type: "integer", enum: [8453], default: 8453 } } },
    outputSchema: { type: "object", required: ["address", "network", "chainId", "safeToProceed", "decision", "riskLevel", "recommendedAction", "eth", "usdc", "checks", "alerts", "limitations", "blockNumber", "observedAt"], properties: { address: { type: "string" }, destinationAddress: { type: ["string", "null"] }, network: { type: "string" }, chainId: { type: "integer" }, safeToProceed: { type: "boolean" }, decision: { type: "string", enum: ["safe_to_pay", "needs_funding", "needs_gas", "review_destination", "reject"] }, riskLevel: { type: "string", enum: ["low", "medium", "high"] }, recommendedAction: { type: "string" }, eth: { type: "string" }, usdc: { type: "string" }, checks: { type: "array", items: { type: "object" } }, alerts: { type: "array", items: { type: "string" } }, limitations: { type: "array", items: { type: "string" } }, blockNumber: { type: "integer" }, observedAt: timestamp } },
  },
  {
    id: "payment-guard",
    name: "Payment Guard",
    mcpTool: "payment_guard",
    operationId: "guardX402Payment",
    tag: "SIGNING SAFETY",
    question: "Does this x402 challenge match my intent?",
    useWhen: "An agent has a live x402 challenge and must validate it immediately before signing.",
    description: "Validate the live x402 challenge, price ceiling, Base network, USDC asset, recipient, buyer funding, and destination hazards immediately before signing.",
    priceUsd: 0.01,
    price: "$0.01",
    amountAtomic: "10000",
    endpoint: "/api/payment-guard",
    maxTimeoutSeconds: 60,
    sampleRequest: { payerAddress: "0x1111111111111111111111111111111111111111", serviceUrl: "https://example.com/api/report", maxAmountUsdc: "0.10", expectedPayTo: "0x2222222222222222222222222222222222222222", minGasReserveEth: "0" },
    sampleResponse: { decision: "safe_to_sign", safeToSign: true, riskLevel: "low", quotedAmountUsdc: "0.01", quotedPayTo: "0x2222222222222222222222222222222222222222", network: NETWORK, asset: USDC, checks: [{ id: "x402_contract", status: "pass" }], alerts: [], recommendedAction: "Sign only the validated payment requirements." },
    inputSchema: { type: "object", additionalProperties: false, required: ["payerAddress", "serviceUrl", "maxAmountUsdc"], properties: { payerAddress: address, serviceUrl: url, maxAmountUsdc: { type: "string", pattern: "^[0-9]+(\\.[0-9]{1,6})?$" }, expectedPayTo: address, minGasReserveEth: { type: "string", pattern: "^[0-9]+(\\.[0-9]{1,18})?$" } } },
    outputSchema: { type: "object", required: ["decision", "safeToSign", "riskLevel", "quotedAmountUsdc", "quotedPayTo", "network", "asset", "checks", "alerts", "recommendedAction"], properties: { decision: { type: "string", enum: ["safe_to_sign", "needs_funding", "review_recipient", "reject"] }, safeToSign: { type: "boolean" }, riskLevel: { type: "string", enum: ["low", "medium", "high"] }, quotedAmountUsdc: { type: "string" }, quotedPayTo: { type: "string" }, network: { type: "string" }, asset: { type: "string" }, checks: { type: "array", items: { type: "object" } }, alerts: { type: "array", items: { type: "string" } }, recommendedAction: { type: "string" } } },
  },
  {
    id: "verify",
    name: "Verify",
    mcpTool: "verify_web_evidence",
    operationId: "verifyUrl",
    tag: "WEB EVIDENCE",
    question: "Can this page be trusted and cited?",
    useWhen: "An agent needs timestamped evidence that a public page is live and contains expected content.",
    description: "Verify one public URL and return status, redirects, metadata, content hash, timestamp, and a stable receipt.",
    priceUsd: 0.01,
    price: "$0.01",
    amountAtomic: "10000",
    endpoint: "/api/verify",
    maxTimeoutSeconds: 300,
    sampleRequest: { url: "https://example.com", expectedStatus: 200, expectedText: "Example Domain" },
    sampleResponse: { verified: true, status: 200, finalUrl: "https://example.com/", contentSha256: "6f5635...", receiptId: "f06d5e...", observedAt: "2026-01-01T00:00:00.000Z" },
    inputSchema: { type: "object", additionalProperties: false, required: ["url"], properties: { url, expectedStatus: { type: "integer", minimum: 100, maximum: 599 }, expectedText: { type: "string", maxLength: 500 } } },
    outputSchema: { type: "object", required: ["verified", "status", "finalUrl", "contentSha256", "receiptId", "observedAt"], properties: { verified: { type: "boolean" }, status: { type: "integer" }, title: { type: ["string", "null"] }, finalUrl: url, redirectChain: { type: "array", items: url }, responseTimeMs: { type: "integer" }, contentSha256: { type: "string" }, receiptId: { type: "string" }, observedAt: timestamp } },
  },
  {
    id: "batch",
    name: "Batch",
    mcpTool: "batch_check_urls",
    operationId: "batchCheckUrls",
    tag: "UP TO 10 URLS",
    question: "Are all these sources usable now?",
    useWhen: "An agent needs to validate up to ten citations, links, or API dependencies in one call.",
    description: "Check up to ten public URLs in one call while isolating partial failures per result.",
    priceUsd: 0.01,
    price: "$0.01",
    amountAtomic: "10000",
    endpoint: "/api/batch",
    maxTimeoutSeconds: 120,
    sampleRequest: { urls: ["https://example.com", "https://www.iana.org/help/example-domains"], expectedStatus: 200 },
    sampleResponse: { verified: true, count: 2, checkedAt: "2026-01-01T00:00:00.000Z", results: [{ status: 200, verified: true }] },
    inputSchema: { type: "object", additionalProperties: false, required: ["urls"], properties: { urls: { type: "array", minItems: 1, maxItems: 10, items: url }, expectedStatus: { type: "integer", minimum: 100, maximum: 599 } } },
    outputSchema: { type: "object", required: ["verified", "count", "checkedAt", "results"], properties: { verified: { type: "boolean" }, count: { type: "integer" }, checkedAt: timestamp, results: { type: "array", items: { type: "object" } } } },
  },
  {
    id: "base-balance",
    name: "Base Balance",
    mcpTool: "base_balance",
    operationId: "getBaseWalletBalance",
    tag: "ONCHAIN DATA",
    question: "What does this Base wallet hold?",
    useWhen: "An agent needs current native ETH and Circle USDC balances rather than a payment decision.",
    description: "Read native ETH and Circle USDC balances, atomic values, and the current Base block height.",
    priceUsd: 0.001,
    price: "$0.001",
    amountAtomic: "1000",
    endpoint: "/api/base-balance",
    maxTimeoutSeconds: 60,
    sampleRequest: { address: "0x1111111111111111111111111111111111111111" },
    sampleResponse: { network: "Base", chainId: 8453, eth: "0", usdc: "0", blockNumber: 12345678, observedAt: "2026-01-01T00:00:00.000Z" },
    inputSchema: { type: "object", additionalProperties: false, required: ["address"], properties: { address } },
    outputSchema: { type: "object", required: ["address", "network", "chainId", "eth", "usdc", "ethAtomic", "usdcAtomic", "blockNumber", "observedAt"], properties: { address: { type: "string" }, network: { type: "string" }, chainId: { type: "integer" }, eth: { type: "string" }, usdc: { type: "string" }, ethAtomic: { type: "string" }, usdcAtomic: { type: "string" }, blockNumber: { type: "integer" }, observedAt: timestamp } },
  },
  {
    id: "check",
    name: "Check",
    mcpTool: "check_url",
    operationId: "checkUrl",
    tag: "FAST URL PREFLIGHT",
    question: "Is this URL reachable?",
    useWhen: "An agent needs a fast reachability check before following a link or calling an API.",
    description: "Confirm status, latency, redirects, and content type for one public URL.",
    priceUsd: 0.001,
    price: "$0.001",
    amountAtomic: "1000",
    endpoint: "/api/check",
    maxTimeoutSeconds: 60,
    sampleRequest: { url: "https://example.com", expectedStatus: 200 },
    sampleResponse: { reachable: true, verified: true, status: 200, finalUrl: "https://example.com/", responseTimeMs: 180, contentType: "text/html", observedAt: "2026-01-01T00:00:00.000Z" },
    inputSchema: { type: "object", additionalProperties: false, required: ["url"], properties: { url, expectedStatus: { type: "integer", minimum: 100, maximum: 599 } } },
    outputSchema: { type: "object", required: ["reachable", "verified", "status", "finalUrl", "responseTimeMs", "observedAt"], properties: { reachable: { type: "boolean" }, verified: { type: "boolean" }, status: { type: "integer" }, finalUrl: url, redirectChain: { type: "array", items: url }, responseTimeMs: { type: "integer" }, contentType: { type: "string" }, observedAt: timestamp } },
  },
  {
    id: "merchant-audit",
    name: "Merchant Audit",
    mcpTool: "merchant_audit",
    operationId: "auditX402Merchant",
    tag: "FULL SELLER DIAGNOSIS",
    question: "What exactly should this merchant change?",
    useWhen: "A merchant needs listing-level evidence, competitor prices, buyer reach, and prioritized fixes.",
    description: "Audit Bazaar rankings, competitor pricing, payment reliability, buyer reach, and Base activity, then return prioritized revenue fixes.",
    priceUsd: 0.25,
    price: "$0.25",
    amountAtomic: "250000",
    endpoint: "/api/merchant-audit",
    maxTimeoutSeconds: 60,
    sampleRequest: { payTo: PAY_TO, queries: ["x402 merchant analytics", "agent treasury"] },
    sampleResponse: { score: 72, grade: "C", actions: ["Improve exact buyer-search language in listing metadata."] },
    inputSchema: { type: "object", additionalProperties: false, required: ["payTo", "queries"], properties: { payTo: address, queries: { type: "array", minItems: 1, maxItems: 5, items: { type: "string", minLength: 2, maxLength: 100 } }, excludePayers: { type: "array", maxItems: 10, items: address } } },
    outputSchema: { type: "object", required: ["auditId", "merchant", "network", "observedAt", "score", "grade", "scoreBreakdown", "summary", "listings", "rankings", "onchain", "actions", "limitations"], properties: { auditId: { type: "string" }, merchant: { type: "string" }, network: { type: "string" }, observedAt: timestamp, score: { type: "integer", minimum: 0, maximum: 100 }, grade: { type: "string", enum: ["A", "B", "C", "D", "F"] }, scoreBreakdown: { type: "object" }, summary: { type: "object" }, listings: { type: "array", items: { type: "object" } }, rankings: { type: "array", items: { type: "object" } }, onchain: { type: "object" }, actions: { type: "array", items: { type: "string" } }, limitations: { type: "array", items: { type: "string" } } } },
  },
];

export function getTool(id) {
  const tool = tools.find((candidate) => candidate.id === id);
  if (!tool) throw new Error(`Unknown tool: ${id}`);
  return tool;
}

export function buildCatalog() {
  return {
    schemaVersion: "1.1",
    updatedAt: "2026-09-03T00:00:00.000Z",
    currency: "USDC",
    network: `Base (${NETWORK})`,
    paymentProtocol: "x402 v2",
    mcpEndpoint: `${SITE_URL}/api/mcp`,
    featured: ["merchant-snapshot", "treasury", "payment-guard"],
    tools: tools.map((tool) => ({
      id: tool.id,
      name: tool.name,
      mcpTool: tool.mcpTool,
      question: tool.question,
      useWhen: tool.useWhen,
      description: tool.description,
      priceUsd: tool.priceUsd,
      price: tool.price,
      endpoint: `${SITE_URL}${tool.endpoint}`,
      sampleRequest: tool.sampleRequest,
      sampleResponse: tool.sampleResponse,
    })),
  };
}

export function buildOpenApi() {
  const paths = Object.fromEntries(tools.map((tool) => [tool.endpoint, {
    get: {
      operationId: `get${tool.operationId[0].toUpperCase()}${tool.operationId.slice(1)}Metadata`,
      summary: `Read ${tool.price} USDC ${tool.name} metadata`,
      responses: { "200": { description: "Free service metadata with the canonical request example" } },
    },
      post: {
        operationId: tool.operationId,
        "x-mcp-tool": tool.mcpTool,
      summary: `${tool.question} — ${tool.price} USDC`,
      description: `${tool.description} No account or API key is required; an unpaid request returns an x402 v2 challenge.`,
      requestBody: { required: true, content: { "application/json": { schema: tool.inputSchema, example: tool.sampleRequest } } },
      responses: {
        "200": { description: "Paid decision-ready result", content: { "application/json": { schema: tool.outputSchema, example: tool.sampleResponse } } },
        "400": { description: "Invalid request" },
        "402": { description: `Payment required: ${tool.price} USDC on Base`, headers: { "PAYMENT-REQUIRED": { description: "Base64-encoded x402 v2 payment requirements", schema: { type: "string" } } } },
        "502": { description: "A required public data source was unavailable" },
        "503": { description: "Payment service temporarily unavailable" },
      },
      "x-x402": { version: 2, network: NETWORK, asset: USDC, amount: tool.amountAtomic, payTo: PAY_TO },
    },
  }]));
  paths["/api/mcp"] = { post: { operationId: "callAnywayPossibleMcp", summary: "Connect to all eight tools over Streamable HTTP", description: "Supports initialize, tools/list, and tools/call. Paid-tool challenges and receipts are carried in MCP x402 metadata.", requestBody: { required: true, content: { "application/json": { schema: { type: "object" } } } }, responses: { "200": { description: "MCP JSON-RPC response" }, "403": { description: "Invalid browser Origin" } } } };
  paths["/api/health"] = { get: { operationId: "getHealth", summary: "Check gateway health and advertised capabilities", responses: { "200": { description: "Service gateway is responding" } } } };
  return {
    openapi: "3.1.0",
    info: { title: "Anyway Possible Agent Decision APIs", version: "11.0.0", description: "Eight account-free, x402-paid decision tools for merchant intelligence, Base payment readiness, signing safety, and verifiable web evidence." },
    servers: [{ url: SITE_URL }],
    paths,
  };
}

export function buildLlmsText() {
  const lines = [
    "# Anyway Possible — Decision Infrastructure for Autonomous Agents",
    "",
    "> Eight account-free, read-only tools that give agents current evidence and a structured next action before they pay, cite, or act.",
    "",
    `Base URL: ${SITE_URL}`,
    `Remote MCP: ${SITE_URL}/api/mcp (Streamable HTTP)` ,
    `Network: Base (${NETWORK})`,
    "Payment: x402 v2, USDC, exact per-call pricing",
    "Authentication: none; unpaid HTTP calls return 402 with PAYMENT-REQUIRED",
    "",
    "## Choose by decision",
    "",
    ...tools.map((tool) => `- ${tool.question} ${tool.endpoint} (${tool.mcpTool}) — ${tool.price} USDC. ${tool.useWhen}`),
    "",
    "## Integration",
    "",
    "1. Prefer MCP: connect the remote endpoint, call tools/list, then select a tool.",
    "2. For HTTP: POST the documented JSON body to the chosen endpoint.",
    "3. Read the 402 PAYMENT-REQUIRED challenge and validate price, network, asset, and recipient.",
    "4. Repeat with PAYMENT-SIGNATURE. Treat HTTP 200 as the paid result.",
    "5. Preserve returned evidence, limitations, observation time, and receipt identifiers.",
    "",
    "## Canonical resources",
    "",
    `- Human documentation: ${SITE_URL}/docs`,
    `- Human result examples: ${SITE_URL}/examples`,
    `- Machine catalog: ${SITE_URL}/catalog.json`,
    `- OpenAPI: ${SITE_URL}/openapi.json`,
    `- Guarded purchase workflow: ${SITE_URL}/guarded-purchase.json`,
    `- Health: ${SITE_URL}/api/health`,
    `- Status: ${SITE_URL}/status`,
    `- Guides: ${SITE_URL}/guides`,
    `- What is x402?: ${SITE_URL}/guides/what-is-x402`,
    `- x402 payment safety: ${SITE_URL}/guides/x402-payment-safety`,
    `- Why an x402 API is not selling: ${SITE_URL}/guides/x402-api-not-selling`,
    "- MCP registry name: com.anywaypossible/agent-utilities",
    "",
    "## Safety boundaries",
    "",
    "Treasury decisions are proceed, fund, review, or reject. Payment preflight validates observable contract and chain state; it does not guarantee identity, legality, sanctions status, contract behavior, or future settlement. URL tools reject private-network destinations, bound response size, and validate redirects.",
  ];
  return `${lines.join("\n")}\n`;
}
